### ISSUE TITLE
help needed to run the programme

### ISSUE THREAD

**Issue by eusinbay** [lsweatman/MMPI_2_Grader#1]
hi,

may i ask what programme do you use to run the files?

thanks in advance

eusinbay

**Comment by lsweatman** [comment]
Sorry about the late response I haven't checked the repo in a while.
I use Visual Studio 2017 Community (it's free) to compile. Once you clone the repo you should be able to double click the .sln file (on the root directory) and it should open it. I just reinstalled Windows 10 so I'll give it a run-through this weekend to make sure there aren't any issues.
Let me know if you have questions!
